#!/bin/bash
version=`cat manifest.json| grep \"version\" | sed -E "s/.*\"(([0-9]+\.)+[0-9]+)\".*/\1/g"`
newVersion=`echo $version | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}'`

sed -i -e "s/\(\"version\": \"\).*\(\",\)/\1$newVersion\2/" manifest.json

zip mercury.zip background.js manifest.json mercury.js popup.html icons/icon-*.png
